export default[
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Airforce",
        "price":1.99,
        "image":"./images/shoe2.jpg"
    },
    {
        "name":"Airforce",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    },
    {
        "name":"Horsebit",
        "price":1.99,
        "image":"./images/shoe1.jpg"
    }
]